### ISSUE TITLE
403 Client Error: Forbidden for url

### ISSUE THREAD

**Issue by mithro** [arcivanov/pypi-cleanup#7]
```
DEBUG:urllib3.connectionpool:https://test.pypi.org:443 "GET /manage/projects/ HTTP/1.1" 200 4680
INFO:root:Deleting pythondata-misc-opentitan version 0.0.post5002
DEBUG:urllib3.connectionpool:https://test.pypi.org:443 "GET /manage/project/pythondata-misc-opentitan/release/0.0.post5002/ HTTP/1.1" 403 None
Traceback (most recent call last):
  File "/home/tansell/.local/bin/pypi-cleanup", line 8, in <module>
    sys.exit(main())
  File "/home/tansell/.local/lib/python3.8/site-packages/pypi_cleanup/__init__.py", line 220, in main
    return PypiCleanup(**vars(args)).run()
  File "/home/tansell/.local/lib/python3.8/site-packages/pypi_cleanup/__init__.py", line 175, in run
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 943, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://test.pypi.org/manage/project/pythondata-misc-opentitan/release/0.0.post5002/
```

**Comment by mithro** [comment]
This seems to be caused by not having given the user "Owner" permission on the module.

**Comment by arcivanov** [comment]
Thanks for describing the known cause.
